TOPDIR = ../../.
include $(TOPDIR)/Make/makedefs 

C++FILES =\
	ThreadObserver.cpp \
	ThreadReporter.cpp \
	WorkCrew.cpp \
	$(NULL)

INC      += -I$(TOPDIR)/include -I.
LIBS     += -lOpenThreads

EXEC = WorkCrew

include $(TOPDIR)/Make/makerules